[shell]
program = "tmux"
args = ["new-session", "-A", "-s", "amg"]

[window]
startup_mode = "Fullscreen"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }

[keyboard]
bindings = [{ key = "V", mods = "Control", action = "Paste" }]

