# Replace with values for the current machine
EFI_DISK=/dev/sda
EFI_PART_NUMBER=1

timedatectl

pacstrap -K /mnt base base-devel linux linux-firmware amd-ucode neovim tmux alacritty networkmanager man-db man-pages texinfo sudo sbctl podman hyprland hyprlock swaybg wofi brightnessctl waybar pipewire pipewire-audio pipewire-pulse pipewire-alsa pipewire-jack bluez bluez-utils git git-lfs htop rclone wl-clipboard grim bind ttf-hack-nerd ttf-liberation noto-fonts-emoji xdg-desktop-portal-hyprland bash-completion flatpak android-tools efibootmgr openssh xorg-xhost wget hypridle
genfstab -U /mnt >> /mnt/etc/fstab

rm -rf /mnt/efi/EFI/Linux
mkdir -p /mnt/efi/EFI/Linux
rm /mnt/boot/initramfs*.img # Removes autogenerated initramfs

efibootmgr --create --disk $EFI_DISK --part $EFI_PART_NUMBER --label "Arch Linux" --loader '\EFI\Linux\arch-linux.efi' --unicode
newboot=$(efibootmgr | grep "Arch Linux" | sed -n 's/Boot\([0-9A-Fa-f]*\).*/\1/p')
efibootmgr -o ${newboot}

arch-chroot /mnt

ln -sf /usr/share/zoneinfo/Europe/Madrid /etc/localtime
hwclock --systohc

systemctl enable NetworkManager
systemctl enable bluetooth
systemctl mask dev-tpmrm0.device
systemctl mask dev-tpm0.device

sbctl create-keys
sbctl enroll-keys -m

passwd -l root
useradd -m -G wheel -s /bin/bash amg
passwd amg

su amg -c "flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"
flatpak override --system --no-talk-name=org.freedesktop.ScreenSaver --no-talk-name=org.freedesktop.UDisks2
flatpak override --user --nofilesystem=xdg-download
flatpak override --user --no-talk-name=org.gtk.vfs
flatpak override --user --no-talk-name=org.gtk.vfs.*
flatpak override --user --nofilesystem=host --nofilesystem=xdg-config/fontconfig --nofilesystem=xdg-config/gtk-3.0 --nofilesystem=xdg-run/gvfsd --nofilesystem=home
flatpak override --user --filesystem=/home/amg/Workspace

./push.sh

locale-gen
mkinitcpio -P

echo "Done, review /etc/cmdline.d/root.conf"
