# Replace with values for the current machine
EFI_DISK=/dev/sda
EFI_PART_NUMBER=1
LUKS_DEVICE=/dev/sda2

timedatectl

# TODO Install from root package list
pacstrap -K /mnt base base-devel linux linux-firmware amd-ucode neovim tmux alacritty networkmanager man-db man-pages texinfo sudo sbctl podman hyprland hyprlock swaybg wofi brightnessctl waybar pipewire pipewire-audio pipewire-pulse pipewire-alsa pipewire-jack bluez bluez-utils git git-lfs htop rclone wl-clipboard grim bind ttf-hack-nerd ttf-liberation noto-fonts-emoji xdg-desktop-portal-hyprland bash-completion flatpak android-tools apparmor efibootmgr
genfstab -U /mnt >> /mnt/etc/fstab

rm -rf /mnt/efi/EFI/Linux
mkdir -p /mnt/efi/EFI/Linux
rm /mnt/boot/initramfs*.img # Removes autogenerated initramfs

rm -rf /mnt/etc/apparmor.d/* # Remove preinstalled apparmor profiles

efibootmgr --create --disk $uefi_disk --part $uefi_part_number --label "Arch Linux" --loader '\EFI\Linux\arch-linux.efi' --unicode
newboot=$(efibootmgr | grep "Arch Linux" | sed -n 's/Boot\([0-9A-Fa-f]*\).*/\1/p')
efibootmgr -o ${newboot}

arch-chroot /mnt

ln -sf /usr/share/zoneinfo/Europe/Madrid /etc/localtime
hwclock --systohc

systemctl enable NetworkManager
systemctl enable bluetooth
systemctl enable apparmor

sbctl create-keys
sbctl enroll-keys -m

passwd -l root
useradd -m -G wheel -s /bin/bash amg
passwd amg

su amg -c "git lfs install"
su amg -c "flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"
flatpak override --system --no-talk-name=org.freedesktop.ScreenSaver --no-talk-name=org.freedesktop.UDisks2

git config --global user.email "andresmargar98@proton.me"
git config --global user.name "AMG"
git config --global init.defaultBranch main
git config --global push.autoSetupRemote true
su - amg -s /bin/bash <<'EOF'
git config --global user.email "andresmargar98@proton.me"
git config --global user.name "AMG"
git config --global init.defaultBranch main
git config --global push.autoSetupRemote true
EOF

./push.sh

locale-gen
mkinitcpio -P

echo "Done!"

