[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "amg"]

[window]
startup_mode = "Fullscreen"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 18
