[project]
name = "aicli"
version = "0.1.0"
description = ""
authors = [{ name = "AMG" }]
dependencies = ["openai"]

[project.scripts]
aicli = "aicli.__main__:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
