#!/usr/bin/env bash
kernel=$(readlink -f /run/current-system/kernel)
initrd=$(readlink -f /run/current-system/initrd)

init=$(echo init=$(jq -r '.["org.nixos.bootspec.v1"].init' /run/current-system/boot.json))
params=$(cat /run/current-system/kernel-params)
allparams="$init $params"

rm /boot/EFI/Linux/nixos.efi

ukify build \
    --linux "$kernel" \
    --initrd "$initrd" \
    --os-release /etc/os-release \
    --cmdline "$allparams" \
    --output /boot/EFI/Linux/nixos.efi

sbctl sign /boot/EFI/Linux/nixos.efi

# We don't remove systemd-boot files, they are not signed anyway and this
# makes this script easier, while not conflicting with the standard nixos installation
