# Base system
FROM debian:latest
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && useradd -m -s /bin/bash amgdev \
    && mkdir -p /home/amgdev/.config \
    && apt-get install -y git curl gcc wget ripgrep tree-sitter-cli \
    && wget https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz \
    && tar xzvf nvim-linux-x86_64.tar.gz \
    && cp -rf ./nvim-linux-x86_64/* /usr/local/ \
    && rm nvim-linux-x86_64.tar.gz \ 
    && rm -rf ./nvim-linux-x86_64 \
    && git clone https://github.com/amgdev9/devenv /home/amgdev/devenv \
    && cp -r /home/amgdev/devenv/nvim-code /home/amgdev/.config \
    && cp -r /home/amgdev/devenv/nvim-debugger /home/amgdev/.config \
    && cp -f /home/amgdev/devenv/.bashrc /home/amgdev/.bashrc \
    && cp -f /home/amgdev/devenv/.inputrc /home/amgdev/.inputrc \
    && mv /home/amgdev/devenv/devenvs /root \
    && mkdir -p /home/amgdev/.cache/nvim-code/codeium \
    && mkdir -p /home/amgdev/.local/share/opencode \
    && mkdir -p /home/amgdev/.config/opencode \
    && chown -R amgdev:amgdev /home/amgdev \
    && su - amgdev -c "curl -fsSL https://opencode.ai/install | bash" \
    && su - amgdev -c "git config --global user.name 'AMG'" \
    && su - amgdev -c "git config --global user.email 'andresmargar98@proton.me'" \
    && su - amgdev -c "git config --global init.defaultBranch main" \
    && su - amgdev -c "git config --global credential.helper store" \
    && echo '\
{\n\
  "$schema": "https://opencode.ai/config.json",\n\
  "lsp": false,\n\
  "provider": {\n\
    "openrouter": {\n\
      "models": {\n\
        "openrouter/free": {}\n\
      }\n\
    }\n\
  }\n\
}\
' >> /home/amgdev/.config/opencode/opencode.json
    
COPY windsurf.json /home/amgdev/.cache/nvim-code/codeium/config.json
COPY .git-credentials /home/amgdev/.git-credentials
COPY opencode-auth.json /home/amgdev/.local/share/opencode/auth.json
USER amgdev 
WORKDIR /home/amgdev/workspace
CMD ["bash"]
