FROM debian:latest
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && useradd -m -s /bin/bash amgdev \
    && mkdir -p /home/amgdev/.config \
    && mkdir -p /home/amgdev/.bin \
    && apt-get install -y git curl gcc wget ripgrep tree-sitter-cli \
    && wget https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz \
    && tar -xzvf nvim-linux-x86_64.tar.gz --strip-components=1 -C /usr/local \
    && rm nvim-linux-x86_64.tar.gz \
    && git clone https://github.com/amgdev9/devenv /home/amgdev/devenv \
    && cp -r /home/amgdev/devenv/nvim-code /home/amgdev/.config \
    && cp -r /home/amgdev/devenv/nvim-debugger /home/amgdev/.config \
    && cp -r /home/amgdev/devenv/opencode /home/amgdev/.config \
    && cp -f /home/amgdev/devenv/.bashrc /home/amgdev/.bashrc \
    && cp -f /home/amgdev/devenv/.inputrc /home/amgdev/.inputrc \
    && mv /home/amgdev/devenv/devenvs /root \
    && mkdir -p /home/amgdev/.cache/nvim-code/codeium \
    && mkdir -p /home/amgdev/.local/share/opencode \
    && mkdir -p /home/amgdev/.config/opencode \
    && chown -R amgdev:amgdev /home/amgdev \
    && su - amgdev -c "\
        curl -fsSL https://opencode.ai/install | bash && \
        git config --global user.name 'AMG' && \
        git config --global user.email 'andresmargar98@proton.me' && \
        git config --global init.defaultBranch main && \
        git config --global credential.helper store && \
        mkdir workspace"

COPY windsurf.json /home/amgdev/.cache/nvim-code/codeium/config.json
COPY .git-credentials /home/amgdev/.git-credentials
COPY opencode-auth.json /home/amgdev/.local/share/opencode/auth.json
USER amgdev 
WORKDIR /home/amgdev/workspace
CMD ["bash"]
