#!/usr/bin/env bash
if [ -z "$1" ]; then
    echo "Usage: $0 <name> [permissions]"
    echo "Error: No argument provided."
    exit 1
fi
CONTAINER_USER=amgdev
FOLDER_NAME=workspace
NAME=$1

podman container exists "$NAME"
EXISTS=$?
RUNNING=$(podman ps --filter "name=$NAME" --filter "status=running" -q)

xhost +local:amg

if [ "$EXISTS" != "0" ]; then
    echo Building container image... 
    if [ -z "$2" ]; then
        echo "You need to specify permissions comma separated: x11,pulseaudio,none"
        exit 1
    fi

    podman build -t "$NAME" -f $HOME/Scripts/Containerfile.dev $HOME/.podman

    VOLUMES=""
    ARGS=""

    # Mount x11 socket 
    # TODO Mount wayland socket instead using security context v1
    if [[ ",$2," == *",x11,"* ]]; then
        echo "Using X11"
        VOLUMES="$VOLUMES -v /tmp/.X11-unix:/tmp/.X11-unix"
    fi

    # Mount pulseaudio socket
    if [[ ",$2," == *",pulseaudio,"* ]]; then
        echo "Using pulseaudio"
        VOLUMES="$VOLUMES -v /run/user/$UID/pulse/native:/run/user/$UID/pulse/native"
    fi

    # Check nvidia gpu presence
    if command -v nvidia-smi &> /dev/null; then
        echo "Using nvidia gpu"
        ARGS="$ARGS --gpus all"
    fi

    podman create -it \
        $VOLUMES \
        $ARGS \
        -P \
        -e DISPLAY=$DISPLAY \
        -e PULSE_SERVER=unix:/run/user/$UID/pulse/native \
        --device /dev/dri \
        --name "$NAME" "$NAME" bash

    podman start -ai "$NAME"
    exit
fi

if [ -z "$RUNNING" ]; then
    echo Starting existing container...
    podman start -ai "$NAME"
    exit
fi

echo Attaching to running container...
podman exec -it "$NAME" bash
