#!/usr/bin/env bash
mapfile -t NAMES < <(podman ps --format "{{.Names}}")
NAME="${NAMES[0]}"
if [ -z "$NAME" ]; then
    NAME=$1
    if [ -z "$NAME" ]; then
        echo "Usage: $0 <name> [--offline]"
        echo "Error: No argument provided."
        exit 1
    fi
fi
IS_OFFLINE=$2

podman network exists dev-net || podman network create dev-net 
podman container exists "$NAME"
EXISTS=$?
RUNNING=$(podman ps --filter "name=$NAME" --filter "status=running" -q)

# Clear clipboard
printf "" | wl-copy && printf "" | wl-copy --primary

# Create wayland sandboxed socket
WAYLAND_PID=""
if [[ "$EXISTS" != 0 || -z "$RUNNING" ]]; then
    if [ ! -S "/run/user/$UID/wayland-sandbox" ]; then
       wl-container /run/user/$UID/wayland-sandbox & 
       echo "Started wayland sandbox"
       WAYLAND_PID=$!
    fi
fi

if [ "$EXISTS" != "0" ]; then
    if [ -z "$(podman images -q devenv)" ]; then
        echo "Image not found, building now..."
        podman build -t devenv -f $HOME/Scripts/Containerfile.dev $HOME/.podman
    fi

    ARGS=""

    # Mount wayland socket
    ARGS="$ARGS -v /run/user/$UID/wayland-sandbox:/tmp/wayland-sandbox -e WAYLAND_DISPLAY=wayland-sandbox"

    # Mount pulseaudio socket
    # TODO Mount pipewire instead 
    # Use pw-container -P '{"pipewire.sec.engine":"podman.devcontainer"}'
    ARGS="$ARGS -v /run/user/$UID/pulse/native:/run/user/$UID/pulse/native -e PULSE_SERVER=unix:/run/user/$UID/pulse/native"

    # Check nvidia gpu presence
    if command -v nvidia-smi &> /dev/null; then
        echo "Using nvidia gpu"
        ARGS="$ARGS --gpus all"
    fi

    # Check internet access 
    if [ -z "$IS_OFFLINE" ]; then
        ARGS="$ARGS --network dev-net -P"
    else
        ARGS="$ARGS --network=none"
    fi

    podman create -it \
        $ARGS \
        -e XDG_RUNTIME_DIR=/tmp \
        --userns=keep-id \
        --device /dev/dri \
        --name "$NAME" devenv bash

    podman start -ai "$NAME"
    if [[ -n "$WAYLAND_PID" ]]; then
        kill -SIGINT $WAYLAND_PID
        echo "Wayland sandbox shut down"
    fi
    exit
fi

if [ -z "$RUNNING" ]; then
    echo Starting existing container...
    podman start -ai "$NAME"
    if [[ -n "$WAYLAND_PID" ]]; then
        kill -SIGINT $WAYLAND_PID
        echo "Wayland sandbox shut down"
    fi
    exit
fi

echo Attaching to running container...
podman exec -it "$NAME" bash
