#!/usr/bin/env bash
CONTAINER_USER=amgdev
FOLDER_NAME=workspace
NAME=$(basename "$PWD")

podman container exists "$NAME"
EXISTS=$?
RUNNING=$(podman ps --filter "name=$NAME" --filter "status=running" -q)

xhost +si:localuser:amg

if [ "$EXISTS" != "0" ]; then
    echo Building container image... 
    podman build -t "$NAME" -f Containerfile $HOME/.podman

    # Mount x11 socket 
    VOLUMES="-v /tmp/.X11-unix:/tmp/.X11-unix"

    # Check nvidia gpu presence
    ARGS=""
    if command -v nvidia-smi &> /dev/null; then
        echo "Using nvidia gpu"
        ARGS="$ARGS --gpus all"
    fi

    podman create -it \
        $VOLUMES \
        $ARGS \
        -P \
        -v /run/user/$UID/pulse/native:/run/user/$UID/pulse/native \
        -e DISPLAY=$DISPLAY \
        -e PULSE_SERVER=unix:/run/user/$UID/pulse/native \
        --device /dev/dri \
        --device /dev/snd \
        --name "$NAME" "$NAME" bash

    podman start -ai "$NAME"
    exit
fi

if [ -z "$RUNNING" ]; then
    echo Starting existing container...
    podman start -ai "$NAME"
    exit
fi

echo Attaching to running container...
podman exec -it "$NAME" bash
