#!/bin/bash
set -e

REPO_NAME=${1:?"Error: Repository name is missing"}
mapfile -t NAMES < <(podman ps --format "{{.Names}}")
CONTAINER_NAME="${NAMES[0]}"
if [ -z "$CONTAINER_NAME" ]; then
    echo "No container running"
    exit 1
fi

BUNDLE_PATH="$HOME/Storage/GitRepos/$REPO_NAME/repo.bundle"

if [ -f "$BUNDLE_PATH" ]; then
    podman cp $BUNDLE_PATH $CONTAINER_NAME:/home/amgdev/_repo.bundle
else
    mkdir -p "$HOME/Storage/GitRepos/$REPO_NAME"
fi

podman exec -i $CONTAINER_NAME bash << EOF
    set -e
    rm -rf /home/amgdev/_repo.git
    if [ -f /home/amgdev/_repo.bundle ]; then
        git clone --bare /home/amgdev/_repo.bundle /home/amgdev/_repo.git
    else
        git init --bare /home/amgdev/_repo.git
    fi
    rm -f /home/amgdev/_repo.bundle
    git -C /home/amgdev/workspace/$REPO_NAME remote remove origin 2>/dev/null || true
    git -C /home/amgdev/workspace/$REPO_NAME remote add origin /home/amgdev/_repo.git
    if [ -d "/home/amgdev/lfs" ]; then
        git -C /home/amgdev/workspace/$REPO_NAME config lfs.url "file:///home/amgdev/lfs"
    fi
    git -C /home/amgdev/workspace/$REPO_NAME push $2
    git -C /home/amgdev/_repo.git bundle create /home/amgdev/_repo.bundle --all
EOF
podman cp $CONTAINER_NAME:/home/amgdev/_repo.bundle $BUNDLE_PATH
podman exec -i $CONTAINER_NAME bash << EOF
    rm -rf /home/amgdev/_repo.git
    rm /home/amgdev/_repo.bundle
EOF
cloud push
