#!/bin/sh

if command -v afplay >/dev/null 2>&1; then
    exec afplay ~/Scripts/ding.wav >/dev/null 2>&1
fi

if command -v paplay >/dev/null 2>&1; then
    exec paplay ~/Scripts/ding.wav >/dev/null 2>&1
fi

if command -v aplay >/dev/null 2>&1; then
    exec aplay ~/Scripts/ding.wav >/dev/null 2>&1
fi

printf '\a' >/dev/null
