#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEVCONTAINERS_DIR="$SCRIPT_DIR/devcontainers"

OUTFILE="Containerfile"

cat "$DEVCONTAINERS_DIR/base.pre" > "$OUTFILE"

for f in "$@"; do
    cat "$DEVCONTAINERS_DIR/$f" >> "$OUTFILE"
done

cat "$DEVCONTAINERS_DIR/base.post" >> "$OUTFILE"

echo "Created $OUTFILE"
