#!/usr/bin/env bash

# Move config to /etc/nixos
rm /etc/nixos/configuration.nix
rm -rf /etc/nixos/nix
cp /home/amg/.config/terminal-config/nixos/configuration.nix /etc/nixos/configuration.nix
cp -r /home/amg/.config/terminal-config/nixos/nix /etc/nixos/nix

# Rebuild and build UKI
nixos-rebuild switch
. /home/amg/Scripts/build-uki

echo
echo "NixOS rebuilt, reboot if needed!"
