#!/usr/bin/env bash

# Move config to /etc/nixos
rm /etc/nixos/configuration.nix
rm /etc/nixos/flake.nix
rm -rf /etc/nixos/nix
cp /home/amg/.config/terminal-config/nixos/configuration.nix /etc/nixos/configuration.nix
cp /home/amg/.config/terminal-config/nixos/flake.nix /etc/nixos/flake.nix
cp -r /home/amg/.config/terminal-config/nixos/nix /etc/nixos/nix

# Rebuild NixOS 
nix-channel --update

HOSTNAME=""
if ! command -v hostname &> /dev/null
then
    read -p "Enter hostname: " HOSTNAME
else
    HOSTNAME=$(hostname)
fi

nixos-rebuild switch --upgrade --flake "/etc/nixos#$HOSTNAME"

# Build UKI
. /home/amg/Scripts/build-uki

echo
echo "NixOS updated, reboot if needed!"
