wireplumber.settings = {
  with-access = true
}

access.permission-managers = [
  {
    name = "block-container-mic"
    default_permissions = "all"
    rules = [
      {
        matches = [
          {
            media.class = "Audio/Source"
          }
        ]
        actions = {
          set-permissions = "-"
        }
      }
    ]
  }
]

access.rules = [
  {
    matches = [
      {
        pipewire.sec.engine = "podman.container"
      }
    ]
    actions = {
      update-props = {
        access = "custom-restricted"
        permission_manager_name = "block-container-mic"
      }
    }
  }
]
